### ISSUE TITLE
 Binary protocol is uncompatible with the Server connected: clientVersion=8, serverVersion=9

### ISSUE THREAD

**Issue by Taygan** [AntonTerekhov/OrientDB-PHP#11]
Hi, 
I am using the latest orientdb-1.0rc9 server as well as the latest OrientDB-PHP release.

I get the following error:

Binary protocol is uncompatible with the Server connected: clientVersion=8, serverVersion=9.

I read your readme which says to use the rc9-SNAPSHOT... just wanted to bring this to your attention.

ALSO, EXCELLENT WORK!!!... your library is awesome and very easy to use.

**Comment by AntonTerekhov** [comment]
Thank you!

Right now protocol version 9 is implemented in `beta-0.4.5`. b2324e39f8

**Comment by AntonTerekhov** [comment]
So, its must be compatible to 1.0rc9. If not - I'll fix it.
`beta-0.4.5` - is a tag, it can be found in Tags section
