### ISSUE TITLE
Record Decoder

### ISSUE THREAD

**Issue by tmaiaroto** [AntonTerekhov/OrientDB-PHP#14]
It doesn't seem to decode the data properly and set it in data. 'data' is empty but 'content' is not. I'm using PHP 5.4

**Comment by AntonTerekhov** [comment]
I ned more info on this: versions, data string that doesn't decode itself.

**Comment by tmaiaroto** [comment]
OrientDB Server version 1.0.1 build 11995
Example string: City@name:"Redmond",country:#18:161
(from the demo database that comes with OrientDB)

Anything else? Thanks for looking into it.

**Comment by AntonTerekhov** [comment]
Well, this works for me:

``` php

<?php

include "OrientDB/OrientDB.php";

$d = new OrientDBRecord();

$d->content = "City@name:\"Redmond\",country:#18:161";

echo 'ClassName: ' . $d->className . "\n";
echo 'name: ' . $d->data->name . "\n";
echo 'country: ' . $d->data->country . "\n";
```

**Comment by AntonTerekhov** [comment]
Result is:

ClassName: City
name: Redmond
country: #18:161

**Comment by tmaiaroto** [comment]
Ah, I see, that does work...But you need to know the fields in order to get at the data. The 'data' field still appears empty when you go to dump the object...I tried a foreach() loop and that works fortunately, but it would be nice to be able to immediately see the data rather than having to call some magic method to get at it because when you try to access $record->data->someFieldThatDoesntExist it'll error out. Even if that returned null, it would be a little nicer. While the database is schema-less, at this point we have the data and know what each field is.

I can just loop for now but that's an unfortunate extra amount of work that should already be done.

Thanks for the clarification.

**Comment by AntonTerekhov** [comment]
Well, imagine this just like an array with keys.

You can use isset() and unset(), you can use foreach(), you'll have E_USER_NOTICE when try to use with nonexitent key. Only thing you can't use alone is var_dump(), you must firstly call to $record->parse(), then use var_dump().

Its just simple but solid design, so right now I can't see any alternative to way how OrientDBRecord is implemented.

**Comment by tmaiaroto** [comment]
K, sounds good. Thanks!
