### ISSUE TITLE
Binary version confliciting

### ISSUE THREAD

**Issue by mustafamahmood** [AntonTerekhov/OrientDB-PHP#2]
hi there,
I am new to the orientdb I have just installed the orientdb and trying to work with it using this PHP library, but at the time of connection it is giving me error please see the exception below.

Uncaught exception 'OrientDBException' with message 'Binary protocol is uncompatible with the Server connected: client=4, server=5' in /usr/local/www/apache22/data/OrientDB-PHP/OrientDB/OrientDB.php:173 Stack trace: #0 /usr/local/www/apache22/data/OrientDB-PHP/OrientDB/Commands/OrientDBCommandAbstract.php(144): OrientDB->setProtocolVersion(5) #1 /usr/local/www/apache22/data/OrientDB-PHP/OrientDB/OrientDB.php(97): OrientDBCommandAbstract->execute() #2 /usr/local/www/apache22/data/OrientDB-PHP/Tests/test1.php(9): OrientDB->__call('connect', Array) #3 /usr/local/www/apache22/data/OrientDB-PHP/Tests/test1.php(9): OrientDB->connect('root', 'D5837262C56289B...') #4 {main} thrown in /usr/local/www/apache22/data/OrientDB-PHP/OrientDB/OrientDB.php on line 173

If I connect it through ssh it works fine but its not working with code can you please advise why this is happening?

Regards,
Mustafa

**Comment by AntonTerekhov** [comment]
Hello Mustafa.

This error is about protocol version conflict. You should use code with compatible Orient server. Version of compatible Orient server is shown in repo's tags.
However, client's version 4 is pretty old. There is at least beta-0.3 committed, which in newer and works with Orient 1.0-RC1.

**Comment by mustafamahmood** [comment]
Hi Anton,
Thanks for your response it was really helpful atleast I know now what is the prob how ever I am unable to download beta-0.3 as I am getting server error while trying to download, can you please help me to get the latest version of the code.
Regards,
Mustafa

-----Original Message-----

**Comment by AntonTerekhov** [comment]
Hmm, seems its related to github team.

But, you migtht try this in a console:
$ git clone git://github.com/AntonTerekhov/OrientDB-PHP.git
Cloning into OrientDB-PHP...
remote: Counting objects: 1265, done.
remote: Compressing objects: 100% (343/343), done.
remote: Total 1265 (delta 950), reused 1221 (delta 917)
Receiving objects: 100% (1265/1265), 190.29 KiB | 255 KiB/s, done.
Resolving deltas: 100% (950/950), done.

$ cd OrientDB-PHP/

$ git checkout 'beta-0.3(1.0rc1_r2824)'
Note: checking out 'beta-0.3(1.0rc1_r2824)'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 48ad408... If instance of OrientDBRecord is using in recordCreate() or recordUpdate(), some instance properties are filled up.

**Comment by mustafamahmood** [comment]
Hi Anton,

That was brilliant, it just worked now I can communicate with orient db and move on with my work, thanks for all your help :). 

Regards,
Mustafa

-----Original Message-----

**Comment by AntonTerekhov** [comment]
You're welcome.
