### ISSUE TITLE
Linking of records

### ISSUE THREAD

**Issue by sanketgupta81** [AntonTerekhov/OrientDB-PHP#28]
Hi 
I am trying to find how to assign a relationship to a record
Lets say we have two records 
1. User data
2. comments
A comment is posted by a user.Hence this is what I want to save
$record = new OrientDBRecord();
    $record->data->title = 'Test Post';
    $record->data->text = "Welcome to Orient";
 The question is how should I do the linking
    $record->data->postedby = "someuser"
 or
    $record->data->postedby = "1:45"
or something else?

**Comment by AntonTerekhov** [comment]
Hi
You must use
`$record->data->postedby = new OrientDBTypeLink('#100:99');`
or
`$record->data->postedby = new OrientDBTypeLink('100:99');`
