### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bugalot** [AntonTerekhov/OrientDB-PHP#29]
Dear Anton,

First of all, I would like to congratulate you about OrientDB-PHP. This is just a great work ! So great that my team working for a semantic-web based company consider to test it as a serious candidate for persistence.

Unfortunately for us, even if your driver fits to our needs, we will not be able to use it. Indeed, the software we are working on is released under GPLv2. As far as I know, it would be illegal to include your driver in our distribution.

Did you consider a more permissive license such as GPLv2 or ApacheV2 (as OrientDB itself)? I think this would  make your driver adopted by a whole range of open source projects.

Best regards, and thanks for the great job!
Jérôme

**Comment by AntonTerekhov** [comment]
Hi, Jerome!

Thank you for good words.

About the license: afaik, new BSD license is very permissive, and surely, items under new BSD can be used in open source.

**Comment by bugalot** [comment]
Hey Anton !

My bad, I did not see that your license was a BSD one. Definitely a good choice then !

Thanks again !

Best regards,
Jérôme
