### ISSUE TITLE
Please Update to current orient db release 1.4.1 or 1.4.2

### ISSUE THREAD

**Issue by flecktainment** [AntonTerekhov/OrientDB-PHP#30]
I always get this error:

Binary protocol is uncompatible with the Server connected: clientVersion=13, serverVersion=15

PHP API workes fine with 1.3.0 of orientDB, but not with 1.4.1

**Comment by bicode** [comment]
check code in file OrientDB.php in line 364

```
    $this->protocolVersion = $version;
    if ($this->protocolVersion != $this->clientVersion) {
        throw new OrientDBException('Binary protocol is uncompatible with the Server connected: clientVersion=' . $this->clientVersion . ', serverVersion=' . $this->protocolVersion);
    }
```

just make the proper comparision, as far is i know version 15 es back guard compatible to version 13...

**Comment by AntonTerekhov** [comment]
Yes, this is the place for quick fix. Especially if you don't need api from 15.

**Comment by Koc** [comment]
@AntonTerekhov there are other exceptions which trows. Can you update your library to new protocols?

**Comment by miconx** [comment]
is there any update planned for the new 1.5 version of orientdb?

**Comment by AntonTerekhov** [comment]
Yes.

**Comment by AntonTerekhov** [comment]
Protocol version 14 is in 5aee47f. Works with 1.4.0 and in compatibility mode for higher versions.
