### ISSUE TITLE
recordUpdate after recordLoad not updating

### ISSUE THREAD

**Issue by bicode** [AntonTerekhov/OrientDB-PHP#31]
Hi, i don't know if is intended this way, but the update statement only work if i add the line with printf, other wise the record does not get updated...

```
        $recordLoaded = $db->recordLoad($clusterID . ':' . $recordPos);
        echo 'Load record result: ' . $recordLoaded . PHP_EOL . PHP_EOL;

        printf('%1$s %2$s first appears in %3$d' . PHP_EOL . PHP_EOL, $recordLoaded->data->FirstName, $recordLoaded->data->LastName, $recordLoaded->data->appearance);

        echo 'Update record...' . PHP_EOL;

        $recordLoaded->data->appearance = 1939;
        $version = $db->recordUpdate($recordLoaded->recordID, $recordLoaded);
```

in the code that we are using we need not to print of the record after loading it, just set any new properties from the POST...

what i mean is that if you comment the printf line this code won't work,

Thank you

**Comment by AntonTerekhov** [comment]
Hi, you need to explicitly parse loaded record before setting new values.
Use `$record->parse();` instead of printing, as accessing to fields performing implicit `parse()`.

**Comment by bicode** [comment]
thank you, that was exactly what i needed.
