### ISSUE TITLE
'graph' type database support

### ISSUE THREAD

**Issue by tomjnsn** [AntonTerekhov/OrientDB-PHP#34]
I'm brand new to OrientDB so I'm just starting to understand graph databases along with your driver.  I noticed down at the very bottom of issues that it only supports databases with a type of 'document' currently.  I'm assuming that's still true, but what would need to be done to support graph type databases?  I did a quick look through the  documentation for the binary protocol and couldn't see any special requirements to use a graph instead of a document type database.  Is it that you want to implement helper classes to support that?

**Comment by andreyvk** [comment]
That'd be a nice to have...

**Comment by tomjnsn** [comment]
I'd be interested in helping with something like that if you wouldn't mind pointing me to what I'm missing about adding in graph type databases.  I'm still fairly new to it (it is just on a side project I'm playing around with it at this point) so I don't know what in the protocol needs to be implemented to enable graph type databases.

**Comment by AntonTerekhov** [comment]
Hello.

There were some issues with this lib and graph type db in encoding query and decoding its results. Only simple ones, like `g.v1.outE` worked ok, something more complex resulted in errors, see #22, `gremlin.php` for example. This remains unresolved and gremlin remains experimental.

I have no idea, what should be fixed, and on which side: php or SQL itself.
