### ISSUE TITLE
Listing clusters or classes

### ISSUE THREAD

**Issue by andreyvk** [AntonTerekhov/OrientDB-PHP#35]
Hi Anton,

I was wondering if it's possible to list clusters or classes with the library. To make a question more generic: how can one issue console commands like, for instance, browsing a class (browse class <class_name>)?

**Comment by AntonTerekhov** [comment]
Hello.

`info class` and `info clusters` are console commands, so they lack strict SQL equivalent. 
As far as I can remember, you cant get list of classes by reading `#0:1` record. Record `#0:2` holds indexes.

List of clusters is returned from `DBOpen` command.

**Comment by andreyvk** [comment]
Thanks, I'll try the #0:1 trick first.

I understand that i can get list of clusters from DBOpen command, but what if list changed and I need to refresh it? This means tearing down and establishing a new connection then?

**Comment by AntonTerekhov** [comment]
#0:1 isn't a trick, its the only way (binary lacks command `info class`). `info clusters` will be available with #6 implementation.

**Comment by andreyvk** [comment]
Cool, thanks Anton :)
