### ISSUE TITLE
Cant create item correctly in database ...

### ISSUE THREAD

**Issue by dmarko484** [AntonTerekhov/OrientDB-PHP#38]
I have very little code that I cant get working properly.  I'm not able to create a proper record in database. Using code below I can create a new item in database Class, I can see (using OrientDB admin interface) that number of records in class increased but the new record is not listed anywhere, using PHP or orientdb web admin. Manualy created records using OrientDB web admin are listed properly, I have even JAVA code with its orientdb driver that works fine, but this one using PHP is not working. Is there something I'm missing here? ... Working with OrientDB 1.7rc1 (but on 1.6.4 was the same)

$record = new OrientDBRecord();
$record->data->name = 'John';
$record->data->email = 'John@gmail.com';
 $db->recordCreate(10, $record);

**Comment by AntonTerekhov** [comment]
Probably, you're missing -> className attribute. As a result, you record inserted into cluster, but not visible in class collection.

**Comment by dmarko484** [comment]
Updated my code as below, but it returns very generic error now:  java.lang.NullPointerException: 

$record = new OrientDBRecord();
$record->data->name = 'John';
$record->data->email = 'John@seznam.cz';
$record->className="Person";
$db->recordCreate(10, $record);

Without classname I can see number of records increased in proper clusted related to Person class. But cant see any data on this item ...

**Comment by AntonTerekhov** [comment]
PHP code seems to be correct. However, last protocol version is this lib is 15, and Orient 1.6.4 has version 19. Protocol must be back compatible [https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol#wiki-Compatibility ] but I've never test it after version 15.

I'll try to see check it a bit later.

**Comment by AntonTerekhov** [comment]
I've tested it with code:

``` php
require_once 'OrientDB/OrientDB.php';

echo 'Connecting to server...' . PHP_EOL;
try {
    $db = new OrientDB('localhost', 2424);
}
catch (Exception $e) {
    die('Failed to connect: ' . $e->getMessage());
}

$clusters = $db->DBOpen($dbName, 'admin', 'admin');

$record = new OrientDBRecord();
$record->data->name = 'John';
$record->data->email = 'John@seznam.cz';
$record->className="Profile";
var_dump($db->recordCreate(14, $record));
```

 Working with OrientDB 1.7rc1, latest version of lib.

```
orientdb {demo}> select * from Profile offset 40 limit 10;

----+------+-----+----------+---------+----+-------+--------------
#   |@RID  |nick |followings|followers|name|surname|email

----+------+-----+----------+---------+----+-------+--------------
0   |#14:40|Yay-2|[0]       |[0]      |Jay |Miner  |null
1   |#14:41|Yay-3|[0]       |[0]      |Jay |Miner  |null
2   |#14:42|Yay-4|[0]       |[0]      |Jay |Miner  |null
3   |#14:43|Yay-5|[0]       |[0]      |Jay |Miner  |null
4   |#14:44|Yay-6|[0]       |[0]      |Jay |Miner  |null
5   |#14:45|Yay-7|[0]       |[0]      |Jay |Miner  |null
6   |#14:46|Yay-8|[0]       |[0]      |Jay |Miner  |null
7   |#14:47|Yay-9|[0]       |[0]      |Jay |Miner  |null
8   |#14:48|Jay  |[0]       |[0]      |Nick|Nolte  |null
9   |#14:49|null |null      |null     |John|null   |John@seznam.cz
```
