### ISSUE TITLE
Does exists any plan to implement getMetadata()

### ISSUE THREAD

**Issue by Evgsurf** [AntonTerekhov/OrientDB-PHP#4]
Or any other way to get metadata ?

**Comment by AntonTerekhov** [comment]
Hi.

A kind of metadata is returned on DBOpen() call.

If you mean something other, can you clarify a bit?

**Comment by Evgsurf** [comment]
I would like to get information about class properties (somethig like "info class XXX")

**Comment by AntonTerekhov** [comment]
Well, "info class XXX" is not a binary connection command, and not a SQL query, it's a console.sh functionality.

So, this command can be added to this driver only if it be supported on Orient's side via binary connection.

**Comment by Evgsurf** [comment]
You are right. I asked about this feature at Orient forum and Luca says to use getMetadata().
I guess getMetadata() should provide information about class metadata. OShema->getClass()->declaredProperies()
Luca recommended ask you about supporting getMetadata() at php ;-)
If binary drivar does not support metadata for classes ... I will findout another ways

**Comment by AntonTerekhov** [comment]
To be precise, its not binary (this) driver unsupports getMetadata(), but this is not supported in binary protocol, or, at least, exposed at protocol spesification http://code.google.com/p/orient/wiki/NetworkBinaryProtocol .
So, first instance is Luca Garulli.

**Comment by AntonTerekhov** [comment]
Well, seem to class schema is located at record position #0:1  and encoded in JSON. #0:2 has indexes description inside.
So, if I get some time, i'll look into it.

**Comment by Evgsurf** [comment]
Ok, it would be nice Anton.

**Comment by AntonTerekhov** [comment]
It took more time, than I expected. 
But from 0.3.3 you can load records #0:0, #0:1, #0:3, where schema and indexes lists are located.
