### ISSUE TITLE
Result is array empty when load record from orientDb 

### ISSUE THREAD

**Issue by kinquang** [AntonTerekhov/OrientDB-PHP#41]
Hi ,
I try get data from each fields.  Although data is displayed in content when I use function load record .But I don't know how to retrieve data in each field.
![question](https://cloud.githubusercontent.com/assets/8375497/3829740/6de6d6b2-1d83-11e4-9b47-69c55627e202.png)
Now I want to get information as :
Name : Quang
Age : 22
How can I do it.
Thank for help.

**Comment by AntonTerekhov** [comment]
https://github.com/AntonTerekhov/OrientDB-PHP#orientdbdata-class

``` php
<?php
echo $record->data->name;
```

**Comment by AntonTerekhov** [comment]
https://github.com/AntonTerekhov/OrientDB-PHP/blob/master/example.php#L79

**Comment by kinquang** [comment]
Thank Anton, :+1:
