### ISSUE TITLE
Help!Data pending

### ISSUE THREAD

**Issue by MongHoang** [AntonTerekhov/OrientDB-PHP#43]
I have problem load data
When I try debug, I can see data in content of OrientRecord but I want to get data as $key->data->Mail.Result return pending. However , when load orther record, some can load. 
 I need for help.
![help](https://cloud.githubusercontent.com/assets/8448544/3919995/268c0bc8-23b1-11e4-8c58-263a22a43cb3.png)

**Comment by MongHoang** [comment]
Hi, I tryed all recored. Only record which I link with Blog is pending. I see content of it diffrent with orthers User@Name:"quang",in_written_by:%AQAAAAIAEgAAAAAAAAAAABIAAAAAAAAAAQ==;,Password:"quang",out_Friend:#17:1,Mail:"quang@gmail.com".
Is  the problem here?

**Comment by AntonTerekhov** [comment]
Well, I guess this field (in_written_by) is serialized with RidBags, and this is that my library doesn't recognize or support.
No estimation on supporting this feature.

**Comment by MongHoang** [comment]
That 's exactly, Can you give me advice for this proplem. I don't know why edge written_by is wrong.!
