### ISSUE TITLE
OrientDBRecordDecoder::decode() and gremlin projection

### ISSUE THREAD

**Issue by red-0ne** [AntonTerekhov/OrientDB-PHP#7]
Hello,
When issuing queries like SELECT gremlin('current') FROM 5:1 php hangs on OrientDBRecordDecoder::decode($content)
While $content is (string) 'gremlin:v[#5:101]'

Is decode() able to parse gremlin results?
Thank you

**Comment by AntonTerekhov** [comment]
Hello.

At this time - definitely no.
I'll look at gremlin manual and try to implement this, but can't predict a date =)
