### ISSUE TITLE
Failed to DBDelete(): java.lang.NullPointerException:

### ISSUE THREAD

**Issue by howl-anderson** [AntonTerekhov/OrientDB-PHP#8]
# php ./example.php

Deleting DB...
Failed to DBDelete(): java.lang.NullPointerException:

**Comment by howl-anderson** [comment]
java -version
java version "1.6.0_22"
OpenJDK Runtime Environment (IcedTea6 1.10.4) (6b22-1.10.4-0ubuntu1~11.04.1)
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)

**Comment by AntonTerekhov** [comment]
Hi.
Could you please provide more information about version of OrientDB and OrientDB-PHP.

**Comment by howl-anderson** [comment]
AntonTerekhov-OrientDB-PHP-07b69f4

orientdb-graphed-1.0rc8

PHP 5.3.5-1ubuntu7.4 with Suhosin-Patch (cli) (built: Dec 13 2011 18:30:11)

php ./example.php (use cli )

2012/2/10 Anton Terekhov
reply@reply.github.com:

**Comment by AntonTerekhov** [comment]
Ok, I'll take a look..

**Comment by howl-anderson** [comment]
Thank you!

2012/2/10 Anton Terekhov
reply@reply.github.com:

**Comment by AntonTerekhov** [comment]
Seems its Orient related issue. Will wait them to fix it

**Comment by AntonTerekhov** [comment]
Well, error still exists, but example now 5f6563c14406ddbe0c2efd3b9290ccd615949dbb more error-safe.
Thanks!

**Comment by howl-anderson** [comment]
Thanks~

2012/3/10 Anton Terekhov
reply@reply.github.com:

**Comment by AntonTerekhov** [comment]
Orient team fixed this bug.
OrientDB-PHP's last tag 0.4.5 with this fix is available
