### ISSUE TITLE
OrientDB->recordCreate() with className

### ISSUE THREAD

**Issue by MrMitch** [AntonTerekhov/OrientDB-PHP#9]
Is it possible to implement a way of creating a record using OrientDB->recordCreate() and by passing the class name as the first argument, instead of the cluster ID (because some classes can use several clusters) ?

**Comment by AntonTerekhov** [comment]
Short answer is: no.

Long one: network call  to RECORD_CREATE requires exact cluster ID, so I can't see any possibility to use class name here. 
Instead, you can use [INSERT SQL](http://code.google.com/p/orient/wiki/SQLInsert) statement, which has support of class name.
After all, you can write a simple classnames-to-clusterIDs mapper and use it in your project to follow low coupling strategy.

**Comment by MrMitch** [comment]
Ok, thanks for your answer. That's what i use at the moment but I was curious about whether or not it was possible.
